name: gulim
description: Flutter project is to solve the most common problems with plants.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  auto_route: ^7.8.4
  hive_flutter: ^1.1.0
  dio: ^5.3.3
  flutter_svg: ^2.0.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  # TO ADD THE GENERATOR
  # dart pub global activate assets_generator
  # TO RUN THE GENERATOR
  # agen --no-watch --type d --save --out lib/common/assets